### PR TITLE
TAGz BASIC CRUD DONE

### PR DESCRIPTION
**Pull request by TriggSumms**
# Description
Setup the foundations of the Tag Management. Currently a user can view all tags, create a new tag, delete the tag, and edit the tag via The navigation Bar. 

# Ticket Reference

- [#13 - View All Tags](https://github.com/nss-day-cohort-41/tabloid-fullstack-crop-circle-cavorters/issues/13)

- [#14 - Create a Tag](https://github.com/nss-day-cohort-41/tabloid-fullstack-crop-circle-cavorters/issues/14)

- [#16 - Edit a Tag](https://github.com/nss-day-cohort-41/tabloid-fullstack-crop-circle-cavorters/issues/16)
 
- [#15 - Delete a tag ](https://github.com/nss-day-cohort-41/tabloid-fullstack-crop-circle-cavorters/issues/15)

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions
-Clone the Repo, Open up your VS .sln file, Execute the two SQL files in the SQL folder, Create a new Firebase User via your project(https://console.firebase.google.com/). *Replace your USER UID Key in the Database with the one from your Authentication Tab in the firebase console and add your Firebase Project Id (Directions are in the Projects ReadMe)

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by TriggSumms** [comment]
Feel free to pull this down and test, we will merge on Monday. Take a look at my edit and delete, and let me know if any questions arise over tha weekend! *The edit section is heavily commented

**Review by chadjones839 — APPROVED** [review]
Full CRUD works on Tags

**Comment by TriggSumms** [comment]
Updated my PR with Master, as I was behind in commits

**Review by victorialherring — APPROVED** [review]
Hell yeah dude!

**Review by zachMcWhirter — APPROVED** [review]
All features working

**Pull request merged**
